import React from 'react';

const CountryInfo = ({ countryName }) => {
    switch (countryName) {
        case 'france':
            return <p>&emsp; France, officially the French Republic, is a country whose territory consists of metropolitan France in Western Europe and several overseas regions and territories.France is a unitary semi-presidential republic with its capital in Paris, the country's largest city and main cultural and commercial centre. Other major urban areas include Lyon, Marseille, Toulouse, Bordeaux, Lille and Nice. France, including its overseas territories, has the most number of time zones of any country, with a total of 12. <br></br>&emsp;France has long been a global centre of art, science, and philosophy. It hosts the world's fifth-largest number of UNESCO World Heritage Sites and is the leading tourist destination, receiving around 83 million foreign visitors annually, but if it counted the nights spent by non-residents tourist, France become the sixth country in world with 138 millions of nights, behind United States, China, Spain, Italy and United Kingdom. France is a developed country with the world's seventh-largest economy by nominal GDP, and the tenth-largest by PPP. In terms of aggregate household wealth, it ranks fourth in the world.[15] France performs well in international rankings of education, health care, life expectancy, and human development. France is considered a great power in global affairs, being one of the five permanent members of the United Nations Security Council with the power to veto and an official nuclear-weapon state. It is a leading member state of the European Union and the Eurozone, and a member of the Group of 7 and North Atlantic Treaty Organization (NATO).</p>;
        case 'italy':
            return <p>&emsp;Italy, officially the Italian Republic, is a European country consisting of a peninsula delimited by the Alps and surrounded by several islands. Italy is located in south-central Europe, and it is also considered a part of western Europe. A unitary parliamentary republic with its capital in Rome, the country covers a total area of 301,340 km2 (116,350 sq mi) and shares land borders with France, Switzerland, Austria, Slovenia, and the enclaved microstates of Vatican City and San Marino.<br></br>&emsp;Today, Italy is considered to be one of the world's most culturally and economically advanced countries, with the world's eighth-largest economy by nominal GDP, sixth-largest national wealth and third-largest central bank gold reserve. It ranks very highly in life expectancy, quality of life, healthcare, and education. The country plays a prominent role in regional and global economic, military, cultural and diplomatic affairs; it is both a regional power and a great power, and is ranked the world's eighth most-powerful military. Italy is a founding and leading member of the European Union and a member of numerous international institutions, including the UN, NATO and the G7. The country has long been a global centre of art, music, literature, philosophy, science and technology, and fashion, and has greatly influenced and contributed to diverse fields including cinema, cuisine, sports, jurisprudence, banking and business. As a reflection of its cultural wealth, Italy is home to the world's largest number of World Heritage Sites, and is the fifth-most visited country.</p>
        case 'egypt':
            return <p>&emsp;Egypt, officially the Arab Republic of Egypt, is a transcontinental country spanning the northeast corner of Africa and southwest corner of Asia by a land bridge formed by the Sinai Peninsula. Egypt is a Mediterranean country bordered by the Gaza Strip and Israel to the northeast, the Gulf of Aqaba and the Red Sea to the east, Sudan to the south, and Libya to the west. Islam is the official religion of Egypt and Arabic is its official language. Egypt is considered to be a regional power in North Africa, the Middle East and the Muslim world, and a middle power worldwide. With one of the largest and most diversified economies in the Middle East, which is projected to become one of the largest in the world in the 21st century, Egypt has the third-largest economy in Africa and the world's 40th-largest economy by nominal GDP. Egypt is a founding member of the United Nations, the Arab League, the African Union, and the Organisation of Islamic Cooperation. <br></br>&emsp;Egypt has one of the oldest civilisations in the world. It has been in contact with many other civilisations and nations and has been through so many eras. Egyptian civilisation is renowned for its colossal pyramids, temples and monumental tombs.</p>
        case 'japan':
            return <p>&emsp;Japan is an island country located in East Asia. It is bordered by the Sea of Japan to the west and the Pacific Ocean to the east, and spans from the Sea of Okhotsk in the north to the East China Sea and Philippine Sea in the south. Part of the Pacific Ring of Fire, Japan encompasses an archipelago of about 6,852 islands, with five main islands (Hokkaido, Honshu, Kyushu, Shikoku, and Okinawa) comprising 97% of the country's area. Japan is divided into 47 prefectures and traditionally into eight regions. Approximately two-thirds of the country's terrain is mountainous and heavily forested, and less than one-eighth of its land is suitable for agriculture. Consequently, Japan is among the most densely populated and urbanized countries in the world. The largest urban area is the metropolitan area centered on the capital city of Tokyo, which is the most populous in the world. <br></br> &emsp;Today, Japan's economy is the world's third-largest by nominal GDP and fourth-largest by purchasing power parity; it is also the fourth-largest importer and exporter and a global leader in the automotive and electronics industries. Japan is ranked "very high" on the Human Development Index; its population enjoys high levels of education and the second-highest life expectancy in the world. Culturally, Japan is renowned for its art, cuisine, literature, cinema, music, and popular culture.</p>
        case 'greece':
            return <p>&emsp;Greece, officially the Hellenic Republic, historically also known as Hellas, is a country located in Southeast Europe. Athens, the nation's capital, is its largest city. Situated on the southern tip of the Balkan Peninsula, Greece is located at the crossroads of Europe, Asia, and Africa. Greece has the longest coastline on the Mediterranean Basin, featuring many islands, of which 227 are inhabited. Eighty percent of Greece is mountainous, with Mount Olympus being the highest peak at 2,918 metres. <br></br>&emsp; Greece is considered the cradle of Western civilisation, being the birthplace of democracy, Western philosophy, Western literature, historiography, political science, major scientific and mathematical principles, Western drama and the Olympic Games. Greece is a unitary parliamentary republic and developed country with an advanced high-income economy, a high quality of life, and a very high standard of living. A founding member of the United Nations, Greece was the tenth member to join the European Communities (precursor to the European Union). It is also a member of numerous other international institutions, including the Council of Europe, the North Atlantic Treaty Organization (NATO) and the World Trade Organization (WTO). Greece's unique cultural heritage, large tourism industry, prominent shipping sector and geostrategic importance classify it as a middle power.</p>
        default: return <p>France, officially the French Republic, is a country whose territory consists of metropolitan France in Western Europe and several overseas regions and territories.France is a unitary semi-presidential republic with its capital in Paris, the country's largest city and main cultural and commercial centre. Other major urban areas include Lyon, Marseille, Toulouse, Bordeaux, Lille and Nice. France, including its overseas territories, has the most number of time zones of any country, with a total of 12. <br></br>&emsp;France has long been a global centre of art, science, and philosophy. It hosts the world's fifth-largest number of UNESCO World Heritage Sites and is the leading tourist destination, receiving around 83 million foreign visitors annually, but if it counted the nights spent by non-residents tourist, France become the sixth country in world with 138 millions of nights, behind United States, China, Spain, Italy and United Kingdom. France is a developed country with the world's seventh-largest economy by nominal GDP, and the tenth-largest by PPP. In terms of aggregate household wealth, it ranks fourth in the world.[15] France performs well in international rankings of education, health care, life expectancy, and human development. France is considered a great power in global affairs, being one of the five permanent members of the United Nations Security Council with the power to veto and an official nuclear-weapon state. It is a leading member state of the European Union and the Eurozone, and a member of the Group of 7 and North Atlantic Treaty Organization (NATO).</p>;

    }
}

function InfoText({ country }) {
    return (
        <div className="CountryInfo_Description">
            <CountryInfo countryName={country}/>
        </div>
    )

}

export default InfoText;






